export const SOCKET_EVENTS = {
  CLIENT: {
    JOIN_GAME: "joinGame",
    LEAVE_GAME: "leaveGame",
    START_GAME: "startGame",
    PLAYER_READY: "playerReady",
    PERFORM_ACTION: "performAction",
    VOTE: "vote",
    FORCE_VOTES: "forceVotes",
    RESTART_GAME: "restartGame",
    SKIP_TO_VOTE: "skipToVote",
    CONFIRM_ROLE_REVEAL: "confirmRoleReveal",
    CHANGE_NAME: "changeName",
    KICK_PLAYER: "kickPlayer",
    REJOIN_GAME: "rejoinGame",
    SETTINGS_UPDATE: "settingsUpdate",
    PING_MEASURE: "pingMeasure",
    REPORT_PING: "reportPing",
    VOICE_JOIN: "voiceJoin",
    VOICE_LEAVE: "voiceLeave",
    VOICE_OFFER: "voiceOffer",
    VOICE_ANSWER: "voiceAnswer",
    VOICE_ICE: "voiceIce",
  },
  SERVER: {
    UPDATE_GAME_SNAPSHOT: "updateGameSnapShot",
    ERROR: "error",
    KICKED: "kicked",
    HOST_TRANSFERRED: "hostTransferred",
    VOICE_NEW_PEER: "voiceNewPeer",
    VOICE_OFFER: "voiceOffer",
    VOICE_ANSWER: "voiceAnswer",
    VOICE_ICE: "voiceIce",
    VOICE_LEAVE: "voiceLeave",
    VOICE_EXISTING_PEERS: "voiceExistingPeers",
  },
} as const;
